In [23]:
import numpy as np

In [ ]:
x = [1,2,3,4,5,6,7]
y = np.array(x)               ## create 1d
print(y)



[1 2 3 4 5 6 7]


In [25]:
y = np.arange(1,5)
y

array([1, 2, 3, 4])

In [26]:
y.size

4

In [27]:
y.shape

(4,)

In [28]:
y.ndim

1

In [29]:
y.dtype

dtype('int64')

In [30]:
y.itemsize

8

In [31]:
y.data

In [32]:
y = np.zeros(5)
y         ## create array

array([0., 0., 0., 0., 0.])

In [33]:
y= np.ones(5)
y

array([1., 1., 1., 1., 1.])

In [ ]:
x = [[1,2,3,4],[5,6,7,8]]          ## 2d
y = np.array(x)
y


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
y = np.arange(2,6,2)
y

array([2, 4])

In [36]:
y.size

2

In [37]:
y.shape

(2,)

In [38]:
y.ndim

1

In [39]:
y.itemsize

8

In [40]:
y.data

In [41]:
y = np.zeros((2,4))
y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
y = np.ones((2,3))
y

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
x = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]]
y = np.array(x)
y

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [44]:
y = np.zeros((3,2,2))
y

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [45]:
y = np.ones((2,2,4))
y

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [46]:
y.size

16

In [47]:
y.ndim

3

In [48]:
y.shape

(2, 2, 4)

In [49]:
y = np.random.rand(3)
y

array([0.4593718 , 0.00499723, 0.80591471])

In [50]:
y = np.random.rand(3,9)
y

array([[0.6367826 , 0.13030885, 0.17987738, 0.52474011, 0.95290977,
        0.64578695, 0.84273226, 0.22628039, 0.0807347 ],
       [0.45016074, 0.29923675, 0.27287559, 0.10087125, 0.77855319,
        0.63254614, 0.11638008, 0.33939573, 0.23241335],
       [0.45755139, 0.94461237, 0.59499455, 0.05359232, 0.48901396,
        0.28221176, 0.42630279, 0.16269498, 0.88875791]])

In [51]:
y = np.random.rand(3,9,2)
y

array([[[6.58913122e-01, 3.85583627e-01],
        [6.04664415e-01, 3.78302051e-01],
        [9.51565425e-01, 5.61096915e-01],
        [6.23308287e-01, 9.04100093e-04],
        [9.97021843e-01, 9.25095598e-01],
        [8.82564502e-01, 6.59175571e-01],
        [3.67804440e-01, 4.24980071e-01],
        [3.39453054e-01, 8.02836683e-01],
        [5.02293317e-01, 9.62593945e-01]],

       [[8.40244058e-01, 1.26349170e-01],
        [1.76028043e-01, 6.07462772e-01],
        [6.71393763e-01, 1.48350265e-01],
        [6.58999021e-01, 3.23658746e-01],
        [8.51202235e-01, 4.46144153e-01],
        [3.23382806e-01, 9.99686446e-02],
        [9.39260854e-01, 2.17000630e-01],
        [1.37091792e-01, 7.86325826e-01],
        [8.47361792e-03, 3.60348504e-01]],

       [[7.08063682e-01, 4.75745730e-01],
        [6.34541281e-01, 8.37946023e-01],
        [4.82465069e-02, 5.72736828e-01],
        [6.49192088e-01, 6.47793517e-01],
        [4.56819433e-01, 7.52275747e-01],
        [9.31064405e-02, 9.016

In [52]:
x = np.empty(4)
x

array([3.42335645e-315, 0.00000000e+000, 5.73116149e-322, 8.70018275e-313])

In [53]:
x = np.empty((4,8))
x

array([[1.  , 0.  , 0.16, 1.  , 1.  , 0.  , 0.  , 1.  ],
       [1.  , 1.  , 0.  , 1.  , 0.  , 1.  , 0.  , 1.  ],
       [0.  , 1.  , 1.  , 1.  , 0.  , 0.  , 1.  , 1.  ],
       [1.  , 0.  , 1.  , 1.  , 1.  , 0.  , 0.75, 1.  ]])

In [54]:
x = np.empty((4,8,2))
x

array([[[8.36551952e-319, 0.00000000e+000],
        [2.33198985e-321,             nan],
        [4.94065646e-322, 1.20480715e+132],
        [4.18680431e-062, 8.04695552e-096],
        [5.88460073e-062, 8.18744134e+140],
        [6.01347002e-154, 1.38133305e-047],
        [1.26931568e-076, 5.88647381e-062],
        [1.26931305e-076, 6.01346953e-154]],

       [[1.57776886e-052, 3.43568691e+179],
        [1.03344127e-047, 3.43506612e+179],
        [5.98149210e-154, 7.42400542e-047],
        [5.35422556e-038, 1.55736719e-033],
        [3.11774072e-033, 1.15298170e-259],
        [6.01347002e-154, 1.02942371e-071],
        [8.04695552e-096, 2.62978245e-052],
        [8.18744134e+140, 6.01347002e-154]],

       [[1.90219989e-052, 1.26931370e-076],
        [1.42670732e-071, 1.26931306e-076],
        [6.01346953e-154, 1.03320477e-047],
        [2.62650097e+179, 5.60157190e-067],
        [2.79048099e+179, 5.98149210e-154],
        [2.63753656e-061, 1.69136211e-052],
        [2.37635375e-038, 6.

In [55]:
x = np.full(1,5)
x

array([5])

In [56]:
x = np.full((2,5),8)
x

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [57]:
x = np.full((3,5,3),9)
x

array([[[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]]])

In [58]:
x= np.array([1,2,3])
y = np.array([-1,-3,4])
n = np.array([0.2,1.5,7.56])
z = np.array([1+2j,2+4j])
m = np.array([True,False])
res = [x.dtype,y.dtype,n.dtype,z.dtype,m.dtype]
print(res)

[dtype('int64'), dtype('int64'), dtype('float64'), dtype('complex128'), dtype('bool')]


In [59]:
x= np.array([1,2,3],dtype = "float32")
x

array([1., 2., 3.], dtype=float32)

In [61]:
z = np.array([1+2j,2+4j],dtype = "int32")
z

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

In [62]:
file = np.array([[1,2,3],[4,5,6]])
np.save("documents.npy",file)

In [63]:
loaded = np.load("documents.npy")
print(loaded)

[[1 2 3]
 [4 5 6]]


In [64]:
np.savetxt("documents.txt",file)

In [65]:
loaded = np.loadtxt("documents.txt")
print(loaded)

[[1. 2. 3.]
 [4. 5. 6.]]


In [79]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x[4])
print(x[3:])
print(x[:-2])
print(x[-2:])
print(x[2:8:2])


5
[4 5 6 7 8 9]
[1 2 3 4 5 6 7]
[8 9]
[3 5 7]


In [68]:
x = np.array([1,2,3,4,5,6,7])
print(x[5])
print(x[-4])


6
4


In [83]:
y = np.array([[1, 3, 5],[7, 9, 2],[4, 6, 8]])
print(y[2,2])
print(y[0,1])
print(y[1])
print(y[2,1:])
print(x[1::3])

8
3
[7 9 2]
[6 8]
[[[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [85]:
x = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])
print(x[1,2,3])
print(x[1,2,1])
print(x[0:3,2:,1:])
print(x[1::3])


24
22
[[[10 11 12]]

 [[22 23 24]]]
[[[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [86]:
x = np.array([1,2,3,4,5,6,7,8])
y = np.reshape(x,(2,2,2))
print(y)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [88]:
x = np.array([1,2,3,4,5,6,7,8])
y = np.reshape(x,(4,2))
print(y)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [89]:


x = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])
y = np.reshape(x,-1)
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [98]:
x = np.array([1, 3, 5, 7])
y = np.array([2, 4, 6, 8])
print(x+y)
res = np.add(x,y)
print(res)
res = np.subtract(x,y)
print(res)
res = np.multiply(x,y)
print(res)
res = np.divide(x,y)
print(res)
print(x**2)
res = np.power(x,3)
print(res)
res = np.mod(x,y)
print(res)
print(x%y)



[ 3  7 11 15]
[ 3  7 11 15]
[-1 -1 -1 -1]
[ 2 12 30 56]
[0.5        0.75       0.83333333 0.875     ]
[ 1  9 25 49]
[  1  27 125 343]
[1 3 5 7]
[1 3 5 7]


In [103]:
x = np.array([[1, 3, 5],[7, 9, 2],[4, 6, 8]])
y = np.array([[1, 4, 6],[7, 3, 1],[2, 3, 7]])
print(x+y)
res = np.add(x,y)
print(res)
res = np.subtract(x,y)
print(res)
res = np.multiply(x,y)
print(res)
res = np.divide(x,y)
print(res)
print(x**2)
res = np.power(x,3)
print(res)
res = np.mod(x,y)
print(res)

print(x%y)
res = np.transpose(y)
print(res)

print(np.sqrt(x))


[[ 2  7 11]
 [14 12  3]
 [ 6  9 15]]
[[ 2  7 11]
 [14 12  3]
 [ 6  9 15]]
[[ 0 -1 -1]
 [ 0  6  1]
 [ 2  3  1]]
[[ 1 12 30]
 [49 27  2]
 [ 8 18 56]]
[[1.         0.75       0.83333333]
 [1.         3.         2.        ]
 [2.         2.         1.14285714]]
[[ 1  9 25]
 [49 81  4]
 [16 36 64]]
[[  1  27 125]
 [343 729   8]
 [ 64 216 512]]
[[0 3 5]
 [0 0 0]
 [0 0 1]]
[[0 3 5]
 [0 0 0]
 [0 0 1]]
[[1 7 2]
 [4 3 3]
 [6 1 7]]
[[1.         1.73205081 2.23606798]
 [2.64575131 3.         1.41421356]
 [2.         2.44948974 2.82842712]]


In [108]:
x = np.array([1,2,8,4,5,2,7,8])
print(np.mean(x))
print(np.median(x))
print(np.min(x))
print(np.max(x))

4.625
4.5
1
8


In [111]:
x = np.array([1,2,8,4,5,2,7,8])
y = np.array([3,4,1,7,5,1,0,6])
print(np.logical_and(x,y))
print(np.logical_or(x,y))
print(np.logical_not(x))


[ True  True  True  True  True  True False  True]
[ True  True  True  True  True  True  True  True]
[False False False False False False False False]


In [119]:
x = np.array([15,25,180,45,60,30])
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))
print(np.degrees(x))
print(np.radians(x))




[ 0.65028784 -0.13235175 -0.80115264  0.85090352 -0.30481062 -0.98803162]
[-0.75968791  0.99120281 -0.59846007  0.52532199 -0.95241298  0.15425145]
[-0.8559934  -0.13352641  1.33869021  1.61977519  0.32004039 -6.4053312 ]
[nan nan nan nan nan nan]
[nan nan nan nan nan nan]
[1.50422816 1.53081764 1.56524083 1.54857776 1.5541312  1.53747533]
[  859.4366927   1432.39448783 10313.24031235  2578.31007809
  3437.74677078  1718.87338539]
[0.26179939 0.43633231 3.14159265 0.78539816 1.04719755 0.52359878]


/tmp/ipython-input-2072014749.py:5: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(x))
/tmp/ipython-input-2072014749.py:6: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(x))


In [122]:
x = np.array([15.123,25.98454,180.67,45.754,60.097,30.456])
print(np.round(x,2))
print(np.floor(x))
print(np.ceil(x))
# print(x)

[ 15.12  25.98 180.67  45.75  60.1   30.46]
[ 15.  25. 180.  45.  60.  30.]
[ 16.  26. 181.  46.  61.  31.]


In [123]:
area = 2 *np.pi*3
print(area)

18.84955592153876


In [124]:
print(np.exp(23))

9744803446.248903


In [126]:
x = np.array([[1, 3, 5],[7, 9, 2],[4, 6, 8]])
y = np.mean(x,axis = 0)
z = np.mean(x,axis = 1)
print(y)
print(z)

[4. 6. 5.]
[3. 6. 6.]


In [128]:
x = np.array([[1, 3, 5],[7, 9, 2],[4, 6, 8]])
y = np.median(x,axis = 0)
z = np.median(x,axis = 1)
print(y)
print(z)

[4. 6. 5.]
[3. 7. 6.]


In [129]:
res = np.percentile(x,25)         ## 25% value is less than or equal to 3.0

print(res)

3.0


In [130]:
res = np.percentile(x,75)
print(res)

7.0


In [2]:
import numpy as np


In [3]:
x = np.array(["hello","good"])
y = np.array(["python","night"])
z = np.char.add(x,y)
print(z)

['hellopython' 'goodnight']


In [5]:
x = np.array(["hello","good"])
print(np.char.multiply((x,y),2))

[['hellohello' 'goodgood']
 ['pythonpython' 'nightnight']]


In [7]:
x = np.array(["hello","good"])
print(np.char.capitalize(x))

['Hello' 'Good']


In [8]:
x = np.array(["hello","good"])
print(np.char.lower(x))

['hello' 'good']


In [9]:
x = np.array(["hello","good"])
print(np.char.upper(x))

['HELLO' 'GOOD']


In [11]:
x = np.array(["hello","good","jeen"])
print(np.char.join("-",x))

['h-e-l-l-o' 'g-o-o-d' 'j-e-e-n']


In [13]:
y = np.array(["hello","Good","jaan"])
print(np.char.equal(x,y))

[ True False False]


In [15]:
x = np.array([1,2,4])
print(x)
y = np.array([[6],[7],[8]])
print(y)
z = np.add(x,y)
print(z)

[1 2 4]
[[6]
 [7]
 [8]]
[[ 7  8 10]
 [ 8  9 11]
 [ 9 10 12]]


In [17]:
x = np.array([1,2,4])
p = 4
res = x + 4
print(res)


[5 6 8]


In [18]:
y = np.array([[6],[7],[8]])
z = 5
print(y + z)

[[11]
 [12]
 [13]]


In [19]:
x = np.array([[1, 3, 5],[7, 9, 2],[4, 6, 8]])
y = np.array([[1, 4, 6],[7, 3, 1],[2, 3, 7]])
matrix = np.dot(x,y)
print(matrix)

[[32 28 44]
 [74 61 65]
 [62 58 86]]


In [21]:
x = np.array([[1, 3, 5],[7, 9, 2],[4, 6, 8]])
y = np.array([[1,6,8],[5,3,9]])
print(np.dot(x,y))               ## for matrix myltiplication dim should be equal

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [22]:
x = np.array([[1, 3, 5],[7, 9, 2],[4, 6, 8]])
print(np.transpose(x))

[[1 7 4]
 [3 9 6]
 [5 2 8]]


In [23]:
x = np.array([[1, 3, 5],[7, 9, 2],[4, 6, 8]])
print(np.linalg.inv(x))

[[-1.11111111 -0.11111111  0.72222222]
 [ 0.88888889  0.22222222 -0.61111111]
 [-0.11111111 -0.11111111  0.22222222]]


In [24]:
x = np.array([[1, 3, 5],[7, 9, 2],[4, 6, 8]])
print(np.linalg.det(x))

-54.00000000000001


In [25]:
x = np.array([1,2,3])
print(np.linalg.det(x))

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

flatten = copy we can't change into original array

reshape = view ,due to this we change the original array

In [28]:
x = np.array([[1, 3, 5],[7, 9, 2],[4, 6, 8]])
print(x.flatten())
print(np.reshape(x,-1))

[1 3 5 7 9 2 4 6 8]
[1 3 5 7 9 2 4 6 8]


In [30]:
x = np.array([[1, 3, 5],[7, 9, 2],[4, 6, 8]])
y = np.array([[3, 2, 8],[-7, 6, 0],[8, 21, 13]])
print(np.union1d(x,y))

[-7  0  1  2  3  4  5  6  7  8  9 13 21]


In [31]:
x = np.array([[1, 3, 5],[7, 9, 2],[4, 6, 8]])
y = np.array([[3, 2, 8],[-7, 6, 0],[8, 21, 13]])
print(np.intersect1d(x,y))

[2 3 6 8]


In [34]:
A = np.array([1, 3, 5])
B = np.array([0, 2, 3])
print(np.setdiff1d(x,y))


[1 4 5 7 9]


In [33]:
x = np.array([[1, 3, 5],[7, 9, 2],[4, 6, 8]])
y = np.array([[3, 2, 8],[-7, 6, 0],[8, 21, 13]])
print(np.setdiff1d(x,y))

[1 4 5 7 9]


In [35]:
x = np.array([[1, 3, 5],[7, 2, 2],[4, 6, 8]])
print(np.unique(x))

[1 2 3 4 5 6 7 8]


In [38]:
x = np.array([1, 3, 5])
y = np.array([0, 2, 3])
print(np.setxor1d(x,y))

[0 1 2 5]


 NumPy Vectorization Vs Python for Loop

In [39]:
import time
start = time.time()
x = np.array([1,2,3,4,5,6,7,8,9,10])
for i in range(len(x)):
  x[i] += 10
end = time.time()           ## takes more time than numpy
print(end - start)

0.00030159950256347656


In [40]:
import time
start = time.time()
x = np.array([1,2,3,4,5,6,7,8,9,10])
res = x + 10
end = time.time()
print(end - start)

0.0002741813659667969


In [49]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
def find_square(y):
  if y < 0:
    return 0
  else:
    return y**2
print(find_square(6))


36


In [51]:
x = np.array([1,-2,3,4,5,6,7,8,9,10])
res = np.vectorize(find_square)
final = res(x)
print(final)

[  1   0   9  16  25  36  49  64  81 100]


masking

In [56]:
x = np.array([1,-2,3,4,5,6,7,8,9,10])
mask =  x%5 ==0
print(x[mask])


[ 5 10]


In [57]:
x = np.array([1,-2,3,4,5,6,7,8,9,10])
new = x.copy()
print(new)

[ 1 -2  3  4  5  6  7  8  9 10]


In [58]:
x = np.array([1,-2,3,4,5,6,7,8,9,10])
boolean_mask = x>4
print(x[boolean_mask])

[ 5  6  7  8  9 10]


fancy inndex

In [62]:
p = np.array([1,-2,3,4,5,6,7,8,9,10])
print(np.argsort(p))
print(np.argsort(-p))

[1 0 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 0 1]


In [63]:
p = np.array([1,-2,3,4,5,6,7,8,9,10])
new = [99,98,97,96]
indices = [2,5,7,3]
p[indices] = new
print(p)

[ 1 -2 99 96  5 98  7 97  9 10]


In [65]:
p = np.random.randint(1,5)
print(p)

3


In [67]:
p = np.random.rand(1,5)
print(p)

[[0.36464499 0.62851739 0.41926627 0.95298235 0.20575491]]


In [69]:
p = np.array([1,-2,3,4,5,6,7,8,9,10])
s = np.random.choice(p)
print(s)

10


In [71]:
p = np.array([1,-2,3,4,5,6,7,8,9,10])
q = np.array([9,5,6,88,90,77,17,80,19,101])
print(np.dot(p,q))
print(np.inner(p,q))


3221
3221


In [73]:
array1 = np.array([[1, 3],
                   [5, 7]])
array2 = np.array([[2, 4],
                   [6, 8]])                   ## query
print(np.inner(array1,array2))


# 1*2+3*4        1*6+3*8
# 5*2+7*4        5*6+7*8


[[14 30]
 [38 86]]


1*2      1*4       1*6        
3*2      3*4       3*6
5*2      5*4       5*6   outer

In [74]:
p = np.array([1,-2,3,4,5,6,7,8,9,10])
q = np.array([9,5,6,88,90,77,17,80,19,101])
print(np.dot(p,q))
print(np.outer(p,q))


# 1*2      1*4       1*6
# 3*2      3*4       3*6
# 5*2      5*4       5*6


3221
[[   9    5    6   88   90   77   17   80   19  101]
 [ -18  -10  -12 -176 -180 -154  -34 -160  -38 -202]
 [  27   15   18  264  270  231   51  240   57  303]
 [  36   20   24  352  360  308   68  320   76  404]
 [  45   25   30  440  450  385   85  400   95  505]
 [  54   30   36  528  540  462  102  480  114  606]
 [  63   35   42  616  630  539  119  560  133  707]
 [  72   40   48  704  720  616  136  640  152  808]
 [  81   45   54  792  810  693  153  720  171  909]
 [  90   50   60  880  900  770  170  800  190 1010]]


In [75]:
x = np.array([[1, 3],
                  [5, 7]])
print(np.linalg.det(x))

-7.999999999999998


solve linear equation

In [76]:
array1 = np.array([[1, 3],
                  [5, 7]])
array2 = np.array([[2, 4],
                  [6, 8]])
print(np.linalg.solve(array1,array2))

[[ 0.5 -0.5]
 [ 0.5  1.5]]
