## Level 1: Basics (Arrays Creation & Properties)

1 Create a 1D NumPy array from 1 to 20.

2 Create a 3×3 matrix with values ranging from 2 to 10.

3 Create a 10-element array of all zeros, all ones, and all 5s.

4 Create a 1D array of 50 random integers between 1 and 100, then find:

Mean, Median, Standard Deviation.

5 Given arr = np.array([1, 2, 3, 4, 5]), convert it into float datatype.

## Level 2: Indexing, Slicing & Reshaping

6 Extract every 2nd element from np.arange(1,21).

7 Reshape np.arange(1,13) into a 3×4 matrix.

8 From the above matrix, extract the 2nd row and the 3rd column.

9 Flatten a 2D array into a 1D array.

10 Replace all even numbers in np.arange(1,11) with -1.

## Level 3: Mathematical Operations

11 Create two arrays of size 5 and perform element-wise:

Addition, Subtraction, Multiplication, Division.

12 Generate a 4×4 identity matrix.

13 Multiply two matrices (A: 2×3, B: 3×2).

14 Find the dot product of [1,2,3] and [4,5,6].

15 Given arr = np.array([3,6,9,12]), compute square root, exponential, and natural log.

## Level 4: Real-world Style (Mini Challenges)

16 Simulate 1000 coin flips (0 = tails, 1 = heads) and count heads vs tails.

17 Create a 5×5 matrix of random integers (10–99).

. Find row-wise max

. Column-wise mean

. Overall sum

18 Create a 1D array of 20 random integers and sort it in ascending order.

19 Normalize an array so that all values lie between 0 and 1.

20 Given arr = np.array([1,2,0,0,4,0]), remove all zeros.

In [ ]:
import numpy as np

In [ ]:
#1
x = np.arange(1,21)   
print(x)

In [ ]:
#2
x = np.arange(2,11)
y = x.reshape(3,3)
print(y)

In [ ]:
#3
x = np.zeros(10)
print(x)

In [ ]:
#3
x = np.ones(10)
print(x)

In [ ]:
#3
x = np.full(10,5)
print(x)

In [ ]:
x = np.random.randn(1,101,50)
# x = np.arange(1,101)
print(x)

In [ ]:
#4
y = np.mean(x)
print(y)

In [ ]:
#4
z = np.median(x)
print(z)

In [ ]:
#4
m = np.std(x)
print(m)

In [ ]:
#5
arr = np.array([1, 2, 3, 4, 5],dtype= "float32")
print(arr)

In [ ]:
#6
x = np.arange(2,21,2)
print(x)

In [ ]:
#7
x = np.arange(1,13)
y = x.reshape(3,4)
print(y)

In [ ]:
#8
print(y[2,3])
print(y[1])
print(y[:3,2:3])

In [ ]:
#9
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.reshape(x,-1)
print(y)

In [ ]:

#10
import numpy as np
x = np.arange(1,11)
print(x)
indices = [1,3,5,7,9]
new = [-1,-1,-1,-1,-1]
x[indices]=new
print(x)


           


In [ ]:
#11
x = np.array([23,21,33,45,90])
y = np.array([18,72,44,70,56])
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))


In [ ]:
##12
x = np.eye(4)
x

In [ ]:
##14
x = np.array([1,2,3])
y = np.array([4,5,6])
print(np.dot(x,y))


In [ ]:
#13
x = np.array([[1,2,3],[5,3,8]])
y = np.array([[9,8],[2,6],[3,7]])
print(np.dot(x,y))

In [ ]:
# 15
arr = np.array([3,6,9,12])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log10(arr))

In [ ]:
#20
arr = np.array([1,2,0,0,4,0])
mask = arr != 0
print(arr[mask])

In [ ]:
#18
x= np.random.randint(1,100,20)
# x
print(np.sort(x))
# print(y)

In [ ]:
#19
arr = np.array([1,2,0,77,4,8])
mean = np.mean(arr)
print(mean)
std = np.std(arr)
normalize = (arr - mean)/std
print(normalize)


normalize = (arr - arr.min()) / (arr.max() - arr.min())  # [0,1] normalization
print(normalize)


In [ ]:
#17
x = np.random.randint(10,99,(5,5))
x
print(x.max(axis = 1))
print(x.mean(axis = 0))
print(x.sum())

In [ ]:
## 16
flip = np.random.randint(0,2,1000)
heads = np.sum(flip == 1)
tails = np.sum(flip == 0)
print(heads,tails)

In [ ]:
x = np.random.randint(1,101,10)        ##(low,high,size)
print(x)

[93 46 35 40 58 32 23 82 63 15]


In [70]:
x = np.random.rand(3,6)
x

array([[0.59228952, 0.65688975, 0.09524645, 0.27993712, 0.72188011,
        0.35231206],
       [0.71907859, 0.01087287, 0.72980461, 0.84903686, 0.91818125,
        0.71305029],
       [0.01184917, 0.78852596, 0.78217101, 0.96620589, 0.86928848,
        0.54433047]])

In [69]:
x = np.random.rand(3,3,4)
x

array([[[0.35165367, 0.85402344, 0.92345972, 0.09676779],
        [0.3133916 , 0.14232279, 0.27402646, 0.5073941 ],
        [0.31022484, 0.81760916, 0.19535979, 0.47902262]],

       [[0.59652524, 0.65623048, 0.31648654, 0.01182496],
        [0.10272493, 0.99614204, 0.28496122, 0.09730207],
        [0.99995518, 0.60707347, 0.3450876 , 0.08444325]],

       [[0.34402949, 0.12506377, 0.59772651, 0.64932631],
        [0.46586318, 0.12054899, 0.62008561, 0.79098686],
        [0.94861429, 0.52182188, 0.17182864, 0.0755725 ]]])

In [72]:
x = np.random.rand(5)
x

array([0.32072646, 0.9144937 , 0.7376968 , 0.72540377, 0.79740668])

🏦 Banking

A bank stores daily ATM withdrawals of 1000 customers.
Generate random withdrawals between 100–10,000 and find:

Average withdrawal

Customer who withdrew the maximum amount

How many customers withdrew less than 500

In [82]:
x = np.random.randint(100,10000,1000)
print(x)
print
avg = np.sum(x)/1000
print(avg)

print(np.max(x))

mask = x < 500
print(np.sum(x[mask]))
print(np.sum(x<500))


[1304 8264 7664 8139 1700 8660  171 2814 9036 3608 3228 7263 4484 6977
 8776 9162 6721 5885 7360 5115  145 9052 3705 9130 4289 6121 4542 2760
 7135 9134 9950 5295 5812 6374  953 3736 7031 3216 8633  698 9543 5230
  389 7126 7629 9442 3074 6268 8895 5522 8824 3584 4721 2979 2294 5429
 3346 3601 6794 1775 5672 5935 2392 7299 5764 9799 3680  196 4645 7533
 8752  268 8490 9211  436 1620  507 2656 6566 8425 9145  968 2867 9212
 6010 7557 9605 2898 2686 5500 3236  173 8742 7594 8123 7200 9386  894
 8897 6782 1348 1984 9899  602 3023 9358 3087 7166 4005  749 2003 1625
 4611 8655 4893 8426 5820 3888 2336 9938 4397 3358 4486 5276 4566 6325
 1154 7721 2572 5894 8656 3593 7492 6030 7180 1495 5790 7260 9020 5574
 3789 3683 8219 8361 4367 4471 1748 8357 5230 8758 7232 7466 2972 8738
 2036 3213  337 2777 6108 1567 8833  791 4243 7617 5041 2335 8999 5852
 8001 2882 8753 5547 2163 9370  208 7326 3514 3682 3415 6412 5371  778
 3708 7495 8135 7610 2586 7003  565 6517 2289 2397 7400 2719 6679 7762
 9810 

In [80]:
print(sum(x))

5076611


A school has marks of 50 students in 5 subjects.
Generate random integers (0–100) in shape (50,5) and compute:

Student with highest average marks

Subject-wise topper

Pass percentage (marks >= 40)

In [100]:
x= np.random.randint(1,100,(50,5))
x
avg = np.mean(x)
print(avg)
print(x.max(axis = 0))
print((np.sum(x>=40) /x.size)*100)
# print()

46.048
[94 99 96 99 97]
55.2


Transport

A cab company records ride durations (in minutes) for 200 rides.
Generate random numbers between 5–120.
Find:

Average ride duration

Number of rides longer than 1 hour

90th percentile ride time (longest 10% rides)

In [ ]:
x = np.random.randint(5,120,500)
x
print(np.mean(x))
print(np.percentile(x,90))

array([ 44,  65, 104,  38, 113,  85,  16,  79,  43,  28,  29,  77,  11,
        92,  70,  27,  80, 116,  46,  19,  73,  36,  62,   6,  10, 106,
        51,  34,  33,  52,  73,  98,  19,  83, 110,  93,  67,  55,  40,
        46,  94,  77,  42,  47,  55, 112,  54,  64,  15,  42, 118,  46,
       111,  40,  33,  79,  25,  50, 119,   6,  67,  97,  93,  11, 112,
        75,  47,  12,  46,   7,  39,  19, 113,  71,  94,  23,  26,  94,
        78,  13,  49,  29,  93,  55,  81, 110, 100,  70,  67,  32,  40,
        18,  38, 117, 114,  29,  59,  66, 106, 110,  20,  59,  86, 107,
        63,  14, 113,  29,  51,  43, 118,  83,   9, 119,  47,  23,  47,
        75,  80,  38, 111,  49,  13,  94, 105, 102,  84,  71,  38,  78,
       119,  74, 105,  38,  41, 103,  74,  44,  90,  36,  35,  49,  83,
        75,  27,  28,  89,  98,  57,  45, 117, 118,  36, 116,  17,  81,
       101,  99,  34,   5,  89,  69,  13,   7,  39,  90,  84,  44,  87,
       108, 100,  26, 109, 118,  39, 108,  43,  68,  71,  16, 11

In [102]:
print(np.mean(x))

61.852


In [103]:
print(np.percentile(x,90))


109.0


Generate blood pressure readings of 500 patients (between 90–180).
Find:

Mean, median, std of BP

How many patients have BP > 140 (hypertension cases)

Create a normalized array (0–1 scale).

In [108]:
x = np.random.randint(90,180,500)
x
print(np.mean(x))
print(np.median(x))
print(np.std(x))
print(np.sum(x>140))
print(x - np.mean(x)/np.std(x))
print((x- np.min(x))/(np.max(x))-np.min(x))


134.208
132.5
26.843038874166243
221
[ 95.00026802 125.00026802 110.00026802 144.00026802 127.00026802
 130.00026802  98.00026802 108.00026802 166.00026802 121.00026802
 138.00026802 112.00026802 128.00026802 163.00026802 116.00026802
 112.00026802 147.00026802 162.00026802 122.00026802  94.00026802
 154.00026802 113.00026802 108.00026802 126.00026802 150.00026802
 166.00026802 104.00026802 154.00026802 112.00026802 172.00026802
  93.00026802 129.00026802 151.00026802 160.00026802  91.00026802
 149.00026802  96.00026802 153.00026802 100.00026802 128.00026802
 109.00026802  88.00026802 113.00026802 100.00026802 151.00026802
 150.00026802 142.00026802 174.00026802 115.00026802 173.00026802
  99.00026802 172.00026802 163.00026802 163.00026802  97.00026802
 125.00026802 108.00026802  96.00026802  98.00026802 158.00026802
 104.00026802  93.00026802 171.00026802 150.00026802 125.00026802
 111.00026802 121.00026802 164.00026802 138.00026802 119.00026802
 158.00026802 139.00026802 167.00026802